name: Build and Push to Artifact Registry

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  PROJECT_ID: kube-ci-cd-427615
  REGION: us-central1
  APP_NAME: go-demo
  REPO_NAME: kube-ci-cd-go-demo

jobs:
  build-push-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: "actions/checkout@v3"

      - name: Auth
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: "Build Image Tag with GAR URL"
        run: |-
          echo TAG=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.APP_NAME }}:${{ github.sha }} >> $GITHUB_ENV

      - name: Build image
        run: docker build . --file Dockerfile --tag ${{ env.TAG }}
        working-directory: ./

      - name: Push image
        run: docker push ${{ env.TAG }}

    # - uses: actions/checkout@v4
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
# job:
#   build-push-artifact:
#     runs-on: ubuntu-latest
#     steps:
#       - name: "Checkout"
#         uses: "actions/checkout@v3"

#       - id: "auth"
#           uses: "google-github-actions/auth@v1"
#           with:
#             credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"

#       - name: "Set up Cloud SDK"
#         uses: "google-github-actions/setup-gcloud@v1"

#       - name: "Use gcloud CLI"
#         run: "gcloud info"

#       - name: "Docker auth"
#         run: |-
#           gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

#       - name: "Build Image Tag with GAR URL"
#         run: |-
#           export TAG=${{ env.REGION }}-docker.pkg.dev/${{ PROJECT_ID }}/${{ REPO_NAME }}/

#       - name: Build image
#         run: docker build . --file Dockerfile --tag $TAG
#         working-directory: ./

#       - name: Push image
#         run: docker push $TAG
